# Generated by Django 5.2.7 on 2025-10-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='region',
            new_name='address',
        ),
    ]
