# Generated by Django 5.2.7 on 2025-10-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='report',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='tracking_id',
            field=models.CharField(db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='ReportNote',
        ),
    ]
