# Generated by Django 5.2.7 on 2025-10-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_region_contact_phone_report_is_anonymous_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='contact_email',
        ),
    ]
