# Generated by Django 5.2.7 on 2025-10-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_region_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_reports', 'Can view confidential reports')]},
        ),
        migrations.AddField(
            model_name='report',
            name='assaulter_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='assaulter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
